# MacSetup Zsh Configuration
# Generated by MacSetup v3.0.0
# This is a template .zshrc file for new Mac setups

# Path to oh-my-zsh
export ZSH="$HOME/.oh-my-zsh"

# Theme
ZSH_THEME="powerlevel10k/powerlevel10k"

# Plugins
plugins=(
    git
    docker
    docker-compose
    kubectl
    terraform
    aws
    npm
    yarn
    python
    golang
    rust
    fzf
    tmux
    zsh-autosuggestions
    zsh-syntax-highlighting
    zsh-completions
)

# Oh My Zsh
source $ZSH/oh-my-zsh.sh

# User configuration
export LANG=en_US.UTF-8
export EDITOR='nvim'
export VISUAL='nvim'

# Homebrew
if [[ -f "/opt/homebrew/bin/brew" ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Aliases
alias ll='eza -la --icons'
alias la='eza -la --icons'
alias lt='eza --tree --icons'
alias cat='bat'
alias find='fd'
alias grep='rg'
alias vim='nvim'
alias dc='docker-compose'
alias k='kubectl'
alias tf='terraform'
alias lg='lazygit'
alias ld='lazydocker'

# Functions
mkcd() { mkdir -p "$1" && cd "$1"; }
backup() { cp "$1" "$1.$(date +%Y%m%d-%H%M%S).bak"; }
extract() {
    if [ -f "$1" ]; then
        case "$1" in
            *.tar.bz2) tar xjf "$1" ;;
            *.tar.gz) tar xzf "$1" ;;
            *.bz2) bunzip2 "$1" ;;
            *.gz) gunzip "$1" ;;
            *.tar) tar xf "$1" ;;
            *.tbz2) tar xjf "$1" ;;
            *.tgz) tar xzf "$1" ;;
            *.zip) unzip "$1" ;;
            *.Z) uncompress "$1" ;;
            *.7z) 7z x "$1" ;;
            *) echo "'$1' cannot be extracted" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}

# Custom prompt
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Load local configuration if exists
# Place any personal/sensitive configuration in ~/.zshrc.local
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local